---
title: "Research"
output: html_document
---
***
### Publications

In the bachelor thesis participate as co-author of the article ["Protein complexes associated with β-catenin differentially influence the differentiation profile of neonatal and adult CD8+ T cells"](https://onlinelibrary.wiley.com/doi/abs/10.1002/jcp.28502). 

 
***
I am currently investigating five types of dementia, I do this through artificial intelligence strategies to identify single nucleotide polymorphisms associated with them. I carry out this project in the laboratory of system biology and translational medicine. 

***
#### Experience
- Laboratory of Systems Biology and Translational Medicine, UAEM - Master thesis development "Identification of biomarkers associated with dementia to propose a cellular system for study." Director: Dr. Heriberto Manuel Rivera. 2018 onwards
- Research Residency in the Laboratory of Cellular Immunology, UAEM - Bachelor thesis: "Evaluation of the association of CBP / β-catenin and p300 / β-catenin in the promoter regions of a selection of Wnt / β-catenin response genes". Director: Dr. Ma. Angélica Santana Calderón. 2016-2017
- Laboratory of Viral Dynamics and Carcinogenesis, UAEM - Participation in the project Molecular typing of human papillomavirus in support of clinical diagnosis ”. Director: Dr. Raúl Peralta Rodríguez. 2016-2017
- Research Stay, UNAM - "Identification and characterization of genes involved in the perception and processing of nociceptive signals in Drosophila melanogaster". Director: Dr. Enrique Reynaud Garza. 2014-2015.
- Research Stay, UAEM - "ASYMETRIC SYNTHESIS OF AMONOPHOSPHONIC ACIDS". Chemical Research Center. 2012